### ISSUE TITLE
Repository takes a lot to clone, due to images

### ISSUE THREAD

**Issue by Misterio77** [Thomashighbaugh/base16-vice-scheme#3]
Hello,
Really like this scheme, but i'm facing a bit of a problem. 
I'm writing a base16 manager, and this specific repository takes a lot of time (and bandwidth) to clone, due to images.
Can you consider hosting them elsewhere and just linking them in the README?
I can do that for you and submit a PR, if that's okay.

**Comment by Thomashighbaugh** [comment]
Sorry I missed this, by a whole year! Wow I guess I got a little distracted, then a little more but I appreciate the interest and have fixed it so it should be a much faster process to clone it and much easier on the bandwidth since no one wants to download all that. If you have any more trouble with it, let me know and hopefully I won't take a year to respond XD
